{
 "title": "SBMS - today view",
 "tags": [
  "sbms",
  "sbms0",
  "solar",
  "electrodacus",
  "battery"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "Live Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SOC",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "State of Charge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Time & Monitor Flags",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Flags",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Monitor Flags\" FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a')",
     "select": [
      [
       { "params": [ "Monitor Flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PV",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Battery Voltage\" * \"PV Total Current\" FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Battery",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Battery Voltage\" * \"Battery Current\"   FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Consumption",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Battery Voltage\" * (\"PV Total Current\"-\"Battery Current\") FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Diversion",
     "measurement": "SBMS_Metrics",
     "query": "SELECT  \"ADC4\" * \"ADC4\" /2.16 FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 FROM \"SBMS_Metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Charged",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"Battery Current\" + ABS(\"Battery Current\"))/2 * \"Battery Voltage\" / 120 / 1000  FROM \"SBMS_Metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Discharged",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (-\"Battery Current\" + ABS(\"Battery Current\"))/2 * \"Battery Voltage\" / 120 / 1000  FROM \"SBMS_Metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Battery Voltage\" * (\"PV Total Current\"-\"Battery Current\") / 120 / 1000 FROM \"SBMS_Metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000 FROM \"SBMS_Metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time to full",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (315 *(100 - \"State of Charge\")  / 100) /  ((\"Battery Current\" +ABS(\"Battery Current\")) / 2 ) * 60 FROM \"SBMS_Metrics\" WHERE time > now() -30s ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Last 15m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (315 *(100 - \"State of Charge\")  / 100) /  ((\"Battery Current\" +ABS(\"Battery Current\")) / 2 ) * 60 FROM \"SBMS_Metrics\" WHERE time > now() -15m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Last 1h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (315 *(100 - \"State of Charge\")  / 100) /  ((\"Battery Current\" +ABS(\"Battery Current\")) / 2 ) * 60 FROM \"SBMS_Metrics\" WHERE time > now() -1h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time to empty",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (315 * \"State of Charge\" / 100) / ((-\"Battery Current\" + ABS(\"Battery Current\"))/2 ) *60 FROM \"SBMS_Metrics\" WHERE time > now() -30s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Last 1h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (315 * \"State of Charge\" / 100) /  (\"PV Total Current\"-\"Battery Current\") / 2 * 60  FROM \"SBMS_Metrics\" WHERE time > now() -1h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Last 24h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (315 * \"State of Charge\" / 100) /  (\"PV Total Current\"-\"Battery Current\") / 2 * 60  FROM \"SBMS_Metrics\" WHERE time > now() -24h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy flow",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "PV power",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"PV Total Current\" * \"Battery Voltage\" FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Consumption",
     "measurement": "SBMS_Metrics",
     "query": "SELECT (\"PV Total Current\"-\"Battery Current\") * \"Battery Voltage\" FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Diversion",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"ADC4\" * \"ADC4\" / 2.16 FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Battery",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Battery Current\" * \"Battery Voltage\" FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  { "title": "Battery Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Battery Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "SBMS_Metrics",
     "query": "SELECT last(\"Battery Voltage\") FROM \"SBMS_Metrics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "SOC",
     "measurement": "SBMS_Metrics",
     "query": "SELECT last(\"Battery Voltage\") FROM \"SBMS_Metrics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "State of Charge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Internal Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Internal Temperature",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "SBMS_Metrics",
     "query": "SELECT (\"Internal Temperature\") FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Internal Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Cell1",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 1\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell2",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 2\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell3",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 3\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell4",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 4\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell5",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 5\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell6",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 6\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell7",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 7\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell8",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 8\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  { "title": "Historical data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Last week",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Produced",
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) WHERE time > now() - 6d  GROUP BY time(1d) TZ('Europe/Ljubljana')\n"
    },
    {
     "alias": "Consumed",
     "query": "SELECT SUM(Energy) FROM ( SELECT \"Battery Voltage\" * (\"PV Total Current\"-\"Battery Current\") / 120 / 1000 AS Energy  FROM \"SBMS_Metrics\"   ) WHERE time > now() - 6d GROUP BY time(1d)  TZ('Europe/Ljubljana')"
    },
    {
     "alias": "Diverted",
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) WHERE time > now() - 6d  GROUP BY time(1d) TZ('Europe/Ljubljana')"
    }
   ]
  },
  {
   "title": "Last 5 weeks",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Produced",
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) WHERE time > now() - 5w GROUP BY time(1w, 4d) TZ('Europe/Ljubljana')\n"
    },
    {
     "alias": "Consumed",
     "query": "SELECT SUM(Energy) FROM ( SELECT \"Battery Voltage\" * (\"PV Total Current\"-\"Battery Current\") / 120 / 1000 AS Energy  FROM \"SBMS_Metrics\"  )  WHERE time > now() - 5w GROUP BY time(1w, 4d)  TZ('Europe/Ljubljana')"
    },
    {
     "alias": "Diverted",
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) WHERE time > now() - 5w GROUP BY time(1w, 4d) TZ('Europe/Ljubljana')"
    }
   ]
  },
  {
   "title": "Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Produced",
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" )"
    },
    {
     "alias": "Diverted",
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) "
    }
   ]
  },
  {
   "title": "2022",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "January - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-01-01 00:00:00' and time < '2022-02-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "January - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-01-01 00:00:00' and time < '2022-02-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "February - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-02-01 00:00:00' and time < '2022-03-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "February - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-02-01 00:00:00' and time < '2022-03-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "March - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-03-01 00:00:00' and time < '2022-04-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "March - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-03-01 00:00:00' and time < '2022-04-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "April - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-04-01 00:00:00' and time < '2022-05-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "April - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-04-01 00:00:00' and time < '2022-05-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "May - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-05-01 00:00:00' and time < '2022-06-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "May - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-05-01 00:00:00' and time < '2022-06-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "June - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-06-01 00:00:00' and time < '2022-07-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "June - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-06-01 00:00:00' and time < '2022-07-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "July - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-07-01 00:00:00' and time < '2022-08-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "July - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-07-01 00:00:00' and time < '2022-08-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "August - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-08-01 00:00:00' and time < '2022-09-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "August - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-08-01 00:00:00' and time < '2022-09-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "September - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-09-01 00:00:00' and time < '2022-10-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "September - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-09-01 00:00:00' and time < '2022-10-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "October - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-10-01 00:00:00' and time < '2022-11-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "October - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-10-01 00:00:00' and time < '2022-11-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "November - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-11-01 00:00:00' and time < '2022-12-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "November - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-11-01 00:00:00' and time < '2022-12-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "December - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2022-12-01 00:00:00' and time < '2023-01-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "December - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2022-12-01 00:00:00' and time < '2023-01-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "2023",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "January - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-01-01 00:00:00' and time < '2023-02-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "January - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-01-01 00:00:00' and time < '2023-02-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "February - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-02-01 00:00:00' and time < '2023-03-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "February - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-02-01 00:00:00' and time < '2023-03-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "March - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-03-01 00:00:00' and time < '2023-04-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "March - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-03-01 00:00:00' and time < '2023-04-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "April - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-04-01 00:00:00' and time < '2023-05-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "April - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-04-01 00:00:00' and time < '2023-05-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "May - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-05-01 00:00:00' and time < '2023-06-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "May - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-05-01 00:00:00' and time < '2023-06-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "June - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-06-01 00:00:00' and time < '2023-07-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "June - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-06-01 00:00:00' and time < '2023-07-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "July - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-07-01 00:00:00' and time < '2023-08-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "July - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-07-01 00:00:00' and time < '2023-08-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "August - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-08-01 00:00:00' and time < '2023-09-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "August - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-08-01 00:00:00' and time < '2023-09-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "September - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-09-01 00:00:00' and time < '2023-10-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "September - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-09-01 00:00:00' and time < '2023-10-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "October - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-10-01 00:00:00' and time < '2023-11-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "October - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-10-01 00:00:00' and time < '2023-11-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "November - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-11-01 00:00:00' and time < '2023-12-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "November - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-11-01 00:00:00' and time < '2023-12-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "December - Produced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM (SELECT (\"PV Total Current\" * \"Battery Voltage\") / 120 / 1000 AS Energy FROM \"SBMS_Metrics\" ) where time  >= '2023-12-01 00:00:00' and time < '2024-01-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "December - Diverted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(Energy) FROM ( SELECT \"ADC4\" * \"ADC4\" / 2.16 / 120 / 1000  AS Energy FROM \"SBMS_Metrics\"   ) where time  >= '2023-12-01 00:00:00' and time < '2024-01-01 00:00:00'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}